Added the EOL notice
freifunkMUC/gluon-packages pull request #19
Opened 2021-06-14 19:16 UTC by GoliathLabs

Good day,
I just added the EOL update nagger package. This will later be used by devices with low flash / RAM, so their respective owners will eventually upgrade to a newer and more powerful device. Inspired by Freifunk Frankfurt & Freifunk Karlsruhe.

2021-06-14 19:48 UTC, krombel requested changes
other SSID required to make it work. Else the next ffmuc-meeting should be used to discuss/approve this.

2021-06-14 19:48 UTC, krombel commented on ffmuc-eol-ssid/luasrc/lib/gluon/upgrade/950-ffmuc-update-nagger
> +	ssid = 'supportende.muenchen.freifunk.net',
This does not work as the max length of SSID strings is 32 characters (while this string are 33)
So I would suggest something with "ffmuc.net" as it is shorter than "muenchen.ffmuc.net"

2021-10-12 20:05 UTC, grische commented
@krombel rebased on top of current main and renamed the SSID according to the last meeting notes end of July

2021-10-22 21:20 UTC, krombel approved these changes
LGTM

2021-10-24 14:30 UTC, merged